name = "sqrl.ca-web24"
pages_build_output_dir = "./dist"

# [[kv_namespaces]]
# binding = "KV"
# id = "<NAMESPACE_ID>"

# [[d1_databases]]
# binding = "DB"
# database_name = "northwind-demo"
# database_id = "<DATABASE_ID>"

[vars]
API_KEY = "QTMw5FZsrfsLRIYv0hsRQr7fuz4sDbBKGRsS6Glp"